const state={view:'home',wallet:false,balance:0,fees:0,coin:'USDC',ledger:[],orders:[],prizes:[],currentBox:null,shipping:{},sellerDrafts:[]};
const boxes=[
{id:'box-1',title:'Creator Premium Vault',seller:'Vault Official',price:1500,category:'ポケカ',trust:99,stock:742,sold:12893,returnRate:'94%',fee:'8%',proof:'0xa91c...7df2',colors:['#8b5cf6','#12d6ff'],tags:['公式検品','高還元','即発送'],prizes:[['PSA10 ピカチュウ系 SAR','0.40%',45000,'🏆'],['人気SARカード','2.10%',12000,'✨'],['SR/ARランダム','18.00%',1800,'💎'],['ポイント還元 600pt','79.50%',600,'🪙']]},
{id:'box-2',title:'Community High Return',seller:'CardLab Seller',price:800,category:'ミックス',trust:94,stock:309,sold:3312,returnRate:'91%',fee:'8%',proof:'0x42bb...19ae',colors:['#f59e0b','#ef4444'],tags:['ユーザー出品','還元重視','低価格'],prizes:[['限定BOX上位賞','0.65%',22000,'🔥'],['人気カードA','4.00%',5200,'🎴'],['ノーマルセット','35.00%',900,'📦'],['ポイント還元 320pt','60.35%',320,'🪙']]},
{id:'box-3',title:'NFT x TCG Hybrid Box',seller:'Web3 Collector',price:1200,category:'NFT',trust:91,stock:188,sold:982,returnRate:'89%',fee:'8%',proof:'0x77ac...ee81',colors:['#22c55e','#06b6d4'],tags:['NFT連動','ウォレット限定','希少'],prizes:[['NFT Pass + Card','0.80%',30000,'🪪'],['Digital Collectible','8.00%',3800,'🧬'],['カードパック','24.00%',1400,'🎁'],['ポイント還元 400pt','67.20%',400,'🪙']]},
{id:'box-4',title:'Beginner Safe Vault',seller:'Verified Seller JP',price:300,category:'低価格',trust:97,stock:1200,sold:9041,returnRate:'86%',fee:'8%',proof:'0x8dfe...028c',colors:['#38bdf8','#6366f1'],tags:['初心者向け','発送早い','低価格'],prizes:[['中当たりカード','2.00%',3500,'⭐'],['AR/SR枠','12.00%',850,'🎴'],['ノーマル枠','46.00%',350,'📦'],['ポイント還元 120pt','40.00%',120,'🪙']]}
];
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem('cvState',JSON.stringify({balance:state.balance,ledger:state.ledger,orders:state.orders,prizes:state.prizes,fees:state.fees,shipping:state.shipping,sellerDrafts:state.sellerDrafts,wallet:state.wallet}))}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('cvState')||'{}'))}catch(e){}}
function yen(n){return '¥'+n.toLocaleString('ja-JP')}function pt(n){return Math.round(n).toLocaleString('ja-JP')+' pt'}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function setView(v){state.view=v;$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v)?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});renderAll()}
function updateBalance(){ $('#balanceChip').textContent=pt(state.balance); $('#balanceLarge')&&($('#balanceLarge').textContent=Math.round(state.balance).toLocaleString('ja-JP')); $('#adminFees')&&($('#adminFees').textContent=pt(state.fees)); $('#walletBtn').textContent=state.wallet?'0xA91c...7dF2':'ウォレット接続'}
function renderMarket(){const grid=$('#boxGrid');if(!grid)return;const q=($('#searchBox')?.value||'').toLowerCase();let arr=boxes.filter(b=>(b.title+b.seller+b.category).toLowerCase().includes(q));const sort=$('#sortBox')?.value;if(sort==='price')arr.sort((a,b)=>a.price-b.price);if(sort==='trust')arr.sort((a,b)=>b.trust-a.trust);if(sort==='popular')arr.sort((a,b)=>b.sold-a.sold);grid.innerHTML=arr.map(b=>`<article class="box-card" style="--c1:${b.colors[0]};--c2:${b.colors[1]}"><div class="box-art"><div class="mini-pack">${b.category}</div></div><h3>${b.title}</h3><p>${b.seller} / Seller Score ${b.trust}</p><div class="tag-row">${b.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="box-meta"><span>1回 ${pt(b.price)}</span><span>在庫 ${b.stock}</span></div><div class="box-meta"><span>還元目安 ${b.returnRate}</span><span>販売 ${b.sold}</span></div><button class="primary full" data-open-box="${b.id}">詳細・ガチャ</button></article>`).join('')}
function openBox(id){state.currentBox=boxes.find(b=>b.id===id);setView('box')}
function renderBox(){const b=state.currentBox;if(!b||!$('#boxDetail'))return;$('#boxDetail').innerHTML=`<div class="detail-grid"><div class="big-art" style="--c1:${b.colors[0]};--c2:${b.colors[1]}"><div class="big-pack">${b.title.split(' ')[0]}<br>VAULT</div></div><section class="panel"><div class="panel-title"><h3>${b.title}</h3><span>${b.category}</span></div><p>${b.seller} が提供する承認済みBOX。景品在庫・排出テーブル・売上分配・Proof Hashを確認してから実行できます。</p><div class="tag-row">${b.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="metric-row"><div><strong>${pt(b.price)}</strong><span>1回価格</span></div><div><strong>${b.returnRate}</strong><span>還元目安</span></div><div><strong>${b.trust}</strong><span>Seller Score</span></div></div><h3>排出テーブル</h3><div class="prize-table">${b.prizes.map(p=>`<div class="prize-row"><span>${p[3]} ${p[0]}</span><span>${p[1]}</span><div><div class="prob-bar"><div style="--w:${Math.min(parseFloat(p[1])*3,100)}%"></div></div></div></div>`).join('')}</div><h3>抽選証明</h3><div class="proof-box">BoxHash: ${b.proof}<br>Commitment: userWallet + boxId + serverSeedHash + solanaSlot</div><button class="primary full" id="drawBtn">${pt(b.price)}でガチャを引く</button><button class="secondary full" style="margin-top:10px" data-view="deposit">残高を追加</button></section></div>`;$('#drawBtn').onclick=drawGacha}
function weightedPrize(b){const r=Math.random()*100;let acc=0;for(const p of b.prizes){acc+=parseFloat(p[1]);if(r<=acc)return p}return b.prizes[b.prizes.length-1]}
async function drawGacha(){const b=state.currentBox;if(!state.wallet){$('#walletModal').classList.add('active');return}if(state.balance<b.price){toast('残高不足です。入金してください');setView('deposit');return}state.balance-=b.price;state.fees+=Math.round(b.price*.08);updateBalance();save();const modal=$('#gachaModal');$('#gachaContent').innerHTML=`<h2>Opening...</h2><div class="opening-pack">VAULT</div><p>Solana slot / server seed / box hash を照合中</p>`;modal.classList.add('active');await new Promise(r=>setTimeout(r,1600));const prize=weightedPrize(b);const id='PZ-'+Math.random().toString(36).slice(2,8).toUpperCase();const proof='0x'+Array.from(crypto.getRandomValues(new Uint8Array(16))).map(x=>x.toString(16).padStart(2,'0')).join('');const item={id,box:b.title,name:prize[0],value:prize[2],icon:prize[3],proof,status:'保管中'};state.prizes.unshift(item);state.ledger.unshift({type:'ガチャ',amount:-b.price,detail:b.title,time:new Date().toLocaleString('ja-JP')});save();renderAll();$('#gachaContent').innerHTML=`<h2>獲得しました</h2><div class="result-prize">${prize[3]}</div><h3>${prize[0]}</h3><p>参考価値 ${pt(prize[2])}</p><div class="proof-box">ProofHash: ${proof}</div><div class="hero-actions"><button class="primary" data-view="vault">獲得品へ</button><button class="secondary" id="againBtn">もう一度引く</button></div>`;$('#againBtn').onclick=drawGacha;$('#gachaContent [data-view="vault"]').onclick=()=>{$('#gachaModal').classList.remove('active');setView('vault')}}
function renderVault(){const el=$('#prizeVault');if(!el)return;if(!state.prizes.length){el.innerHTML='<div class="panel"><h3>獲得品はまだありません</h3><p>BOXを引くとここに保管され、発送またはポイント還元を選べます。</p></div>';return}el.innerHTML=state.prizes.map(p=>`<article class="vault-card"><div class="prize-thumb">${p.icon}</div><h3>${p.name}</h3><p>${p.box}</p><div class="tag-row"><span class="tag">${p.status}</span><span class="tag">${pt(p.value)}</span></div><div class="proof-box">${p.proof}</div><div class="vault-actions"><button class="primary" data-ship="${p.id}">発送</button><button class="secondary" data-refund="${p.id}">pt還元</button></div></article>`).join('')}
function renderOrders(){const el=$('#orderList');if(!el)return;el.innerHTML=state.orders.length?state.orders.map(o=>`<div class="order-item"><div><b>${o.title}</b><br><span>${o.type} / ${o.time}</span></div><strong>${o.status}</strong></div>`).join(''):'<p class="note">発送依頼・還元履歴はまだありません。</p>'}
function renderLedger(){const el=$('#ledgerList');if(!el)return;el.innerHTML=state.ledger.length?state.ledger.slice(0,8).map(l=>`<div class="ledger-item"><div><b>${l.type}</b><br><span>${l.detail}</span></div><strong>${l.amount>0?'+':''}${pt(l.amount)}</strong></div>`).join(''):'<p class="note">入出金履歴はまだありません。</p>'}
function renderFeed(){const names=['mika','crypto_taro','seller_07','cardhunter','vault_user'];const acts=['Creator PremiumでSAR枠を獲得','Community Boxを出品','発送依頼を作成','USDC入金が反映','ポイント還元を実行'];const html=Array.from({length:5},(_,i)=>`<div class="activity-item"><div><b>${names[(Date.now()/1000+i|0)%names.length]}</b><br><span>${acts[(Date.now()/1300+i|0)%acts.length]}</span></div><strong>${i+1}分前</strong></div>`).join('');$('#activityList')&&($('#activityList').innerHTML=html);$('#miniFeed')&&($('#miniFeed').innerHTML=html.split('</div>').slice(0,3).join('</div>'))}
function renderSeller(){const payout=$('#sellerPayout');if(payout){const price=Number($('#sellerPrice').value||0);payout.textContent=pt(price*.92)+'/回'}const ed=$('#prizeEditor');if(ed&&!ed.children.length){[['上位賞カード',0.5,30000],['中当たりカード',6,5000],['通常枠',43.5,900],['ポイント還元',50,300]].forEach(addPrizeRow)}const q=$('#sellerQueue');if(q)q.innerHTML=state.sellerDrafts.length?state.sellerDrafts.map(d=>`<div class="activity-item"><div><b>${d.title}</b><br><span>${d.price}pt / ${d.category} / 審査待ち</span></div><strong>Review</strong></div>`).join(''):'<p class="note">作成したBOXはここに審査待ちとして表示されます。</p>'}
function addPrizeRow(row=['新規景品',1,1000]){const ed=$('#prizeEditor');const div=document.createElement('div');div.className='editor-row';div.innerHTML=`<input value="${row[0]}"><input type="number" value="${row[1]}"><input type="number" value="${row[2]}"><button>×</button>`;div.querySelector('button').onclick=()=>div.remove();ed.appendChild(div)}
function renderChecklist(){const items=['Solana Pay入金検証API','本人確認/KYC導線','古物営業・景品表示・資金決済の法務確認','景品検品/倉庫オペレーション','抽選ロジック第三者監査','返金/返品/発送遅延ポリシー','不正検知とレート制限','カスタマーサポート導線'];const el=$('#checklist');if(el)el.innerHTML=items.map((x,i)=>`<label class="check"><input type="checkbox" ${i<2?'checked':''}><span>${x}</span></label>`).join('')}
function renderAll(){updateBalance();renderMarket();renderBox();renderVault();renderOrders();renderLedger();renderFeed();renderSeller();renderChecklist()}
function init(){load();renderAll();setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'});renderFeed();},4000);document.body.addEventListener('click',e=>{const v=e.target.closest('[data-view]')?.dataset.view;if(v)setView(v);const bid=e.target.closest('[data-open-box]')?.dataset.openBox;if(bid)openBox(bid);const ship=e.target.closest('[data-ship]')?.dataset.ship;if(ship){const p=state.prizes.find(x=>x.id===ship);p.status='発送依頼済み';state.orders.unshift({title:p.name,type:'発送依頼',status:'受付済み',time:new Date().toLocaleString('ja-JP')});save();toast('発送依頼を作成しました');renderAll()}const ref=e.target.closest('[data-refund]')?.dataset.refund;if(ref){const idx=state.prizes.findIndex(x=>x.id===ref);const p=state.prizes[idx];const amount=Math.round(p.value*.72);state.balance+=amount;state.ledger.unshift({type:'ポイント還元',amount,detail:p.name,time:new Date().toLocaleString('ja-JP')});state.orders.unshift({title:p.name,type:'ポイント還元',status:'完了',time:new Date().toLocaleString('ja-JP')});state.prizes.splice(idx,1);save();toast(pt(amount)+'を還元しました');renderAll()}});
$('#walletBtn').onclick=()=>$('#walletModal').classList.add('active');$('#closeWallet').onclick=()=>$('#walletModal').classList.remove('active');$('#connectDemo').onclick=()=>{state.wallet=true;save();updateBalance();$('#walletModal').classList.remove('active');toast('ウォレットを接続しました')};$('#closeGacha').onclick=()=>$('#gachaModal').classList.remove('active');
$('#coinTabs')?.addEventListener('click',e=>{if(e.target.dataset.coin){state.coin=e.target.dataset.coin;$$('#coinTabs button').forEach(b=>b.classList.toggle('active',b.dataset.coin===state.coin));updateConversion()}});$('#depositAmount')?.addEventListener('input',updateConversion);function updateConversion(){const amt=Number($('#depositAmount').value||0);$('#conversionText').textContent= state.coin==='USDC'?`${amt} USDC = ${pt(amt*150)}`:`${amt} SOL = ${pt(amt*22000)}`}
$('#simulateDeposit').onclick=()=>{if(!state.wallet){$('#walletModal').classList.add('active');return}const amt=Number($('#depositAmount').value||0);const points=state.coin==='USDC'?amt*150:amt*22000;state.balance+=points;state.ledger.unshift({type:'入金',amount:points,detail:`${amt} ${state.coin}`,time:new Date().toLocaleString('ja-JP')});save();renderAll();toast('着金を確認しました')};$('#copyAddress').onclick=()=>{navigator.clipboard?.writeText($('#depositAddress').textContent);toast('アドレスをコピーしました')};
$('#searchBox')?.addEventListener('input',renderMarket);$('#sortBox')?.addEventListener('change',renderMarket);$('#sellerPrice')?.addEventListener('input',renderSeller);$('#addPrize').onclick=()=>addPrizeRow();$('#createBox').onclick=()=>{state.sellerDrafts.unshift({title:$('#sellerTitle').value,price:$('#sellerPrice').value,category:$('#sellerCategory').value});save();toast('審査用BOXを作成しました');renderSeller()};$('#saveShipping').onclick=()=>{state.shipping={name:$('#shipName').value,phone:$('#shipPhone').value,address:$('#shipAddress').value};save();toast('発送先を保存しました')};updateConversion()}
init();
